#docker-compose up -d
version: '2'

services:

    hellojenkins:
      image: hellojenkins
      container_name: v-hellojenkins
      restart: always
      build:
         context: .
      ports:
         - "8090:8080"
